### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by pushpinderpalsingh** [coding-blocks/CBOnlineApp-iOS#10]
gitignore is not configured in this repository. Adding all the pods to a repo will be increasing the size of the repository with no particular advantage. A developer can download all the pods after cloning the project and running pod install

**Comment by aggarwalpulkit596** [comment]
I'll do this one

**Comment by pushpinderpalsingh** [comment]
@aggarwalpulkit596  Ok. But if you want you can merge my pr I don't want any bounty for this pr.
