### ISSUE TITLE
Fastlane for ScreenShots

### ISSUE THREAD

**Issue by pushpinderpalsingh** [coding-blocks/CBOnlineApp-iOS#7]
Fastlane is a very vast tool. I want to automate screenshots using Fastlane. This will help to check the UI of the app over a vast range of devices automatically. The screenshots can also be used when the app is finally in the App Store. Fastlane can also be used for Continous Delivery but I don't think it is relevant right now as we are in the development phase

**Comment by aggarwalpulkit596** [comment]
Fastlane or Continuous Integration or UnitTest none of them are relevant as the project hasn't even started first start building the project then we can think about all of these features wouldn't take much time
